### ISSUE TITLE
Missing Recipes, Broken(?) Names

### ISSUE THREAD

**Issue by BoyarRex** [anqingchen/Rustic-Witchcraft#1]
![2019-12-28_20 02 41](https://user-images.githubusercontent.com/39660839/71551246-b3751880-29b0-11ea-964c-2c62708fc2f3.png) 
 
![2019-12-28_20 42 26](https://user-images.githubusercontent.com/39660839/71551318-e5877a00-29b2-11ea-971a-992227df728d.png)
Names broken on all furniture items, only Cypress and Elder chair/table recipes are missing.

**Comment by anqingchen** [comment]
Updating now
